name: Compilation APK Benne

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurer Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configurer Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.5'

      - name: Creer la structure Flutter
        run: |
          flutter create --platforms=android .
          rm lib/main.dart
          mv main.dart lib/main.dart
          flutter pub add flutter_bluetooth_serial permission_handler

      - name: Forcer SDK Android 21 et Reparer le Namespace Bluetooth
        run: |
          # 1. Ajustement de la version minimale d'Android
          sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle
          
          # 2. Localiser le fichier de l'extension Bluetooth et y injecter physiquement le namespace requis
          BT_BUILD_GRADLE=$(find ~/.pub-cache -name "build.gradle" | grep "flutter_bluetooth_serial")
          if [ -f "$BT_BUILD_GRADLE" ]; then
            sed -i '/android {/a \    namespace "io.github.edufolly.flutter_bluetooth_serial"' "$BT_BUILD_GRADLE"
            echo "Namespace injecte avec succes dans : $BT_BUILD_GRADLE"
          else
            echo "Fichier de l'extension introuvable dans le cache"
          fi

      - name: Compiler l'APK Release
        run: flutter build apk --split-per-abi

      - name: Archiver l'APK final
        uses: actions/upload-artifact@v4
        with:
          name: telecommande-benne-apk
          path: build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
